; Auto generated by ClangVMP v1.1.2

%_ZN12CoroutineRef7coawaitEv.Frame = type { ptr, ptr, %"struct.CoroutineDef::task::promise_type", i2, %"struct.std::__1::suspend_never", %"struct.CoroutineDef::awaiter", %"struct.std::__1::suspend_never" }

; Function Attrs: mustprogress noinline nounwind optnone ssp
define i64 @_ZN12CoroutineRef7coawaitEv() #0 {
  %1 = alloca %"struct.CoroutineDef::task", align 8
  %2 = alloca %"struct.CoroutineDef::task::promise_type", align 8
  %3 = alloca %"struct.std::__1::suspend_never", align 1
  %4 = alloca %"struct.std::__1::suspend_never", align 1
  %5 = alloca %"struct.CoroutineDef::awaiter", align 1
  %6 = alloca %"struct.std::__1::suspend_never", align 1
  %7 = alloca %"struct.std::__1::suspend_never", align 1
  br i1 true, label %10, label %8

8:                                                ; preds = %0
  %9 = phi ptr [ null, %0 ]
  br label %14

10:                                               ; preds = %0
  %11 = call noalias noundef nonnull ptr @_Znwm(i64 noundef 32) #6
  br label %12

12:                                               ; preds = %10
  %13 = phi ptr [ %11, %10 ]
  br label %14

14:                                               ; preds = %8, %12
  %15 = phi ptr [ %9, %8 ], [ %13, %12 ]
  %16 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 0
  store ptr @_ZN12CoroutineRef7coawaitEv.resume, ptr %16, align 8
  %17 = select i1 true, ptr @_ZN12CoroutineRef7coawaitEv.destroy, ptr @_ZN12CoroutineRef7coawaitEv.cleanup
  %18 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 1
  store ptr %17, ptr %18, align 8
  br label %19

19:                                               ; preds = %14
  %20 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 4
  %21 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 5
  %22 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 6
  %23 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 2
  br label %24

24:                                               ; preds = %19
  %25 = call noundef ptr @_ZN12CoroutineDef4task12promise_typeC1Ev(ptr noundef nonnull align 8 dereferenceable(8) %23)
  %26 = call i64 @_ZN12CoroutineDef4task12promise_type17get_return_objectEv(ptr noundef nonnull align 8 dereferenceable(8) %23)
  %27 = getelementptr inbounds %"struct.CoroutineDef::task", ptr %1, i32 0, i32 0
  %28 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %27, i32 0, i32 0
  %29 = inttoptr i64 %26 to ptr
  store ptr %29, ptr %28, align 8
  call void @_ZN12CoroutineDef4task12promise_type15initial_suspendEv(ptr noundef nonnull align 8 dereferenceable(8) %23)
  %30 = call noundef zeroext i1 @_ZNKSt3__113suspend_never11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %20) #7
  br i1 %30, label %40, label %31

31:                                               ; preds = %24
  %32 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 3
  store i2 0, ptr %32, align 1
  br label %33

33:                                               ; preds = %31
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_init(ptr %20, ptr %15) #7
  br label %34

34:                                               ; preds = %33
  br label %35

35:                                               ; preds = %34
  br label %36

36:                                               ; preds = %35
  switch i8 -1, label %98 [
    i8 0, label %40
    i8 1, label %37
  ]

37:                                               ; preds = %36
  br label %38

38:                                               ; preds = %37
  %39 = phi i32 [ 2, %37 ]
  br label %43

40:                                               ; preds = %36, %24
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %20) #7
  br label %41

41:                                               ; preds = %40
  %42 = phi i32 [ 0, %40 ]
  br label %43

43:                                               ; preds = %41, %38
  %44 = phi i32 [ %42, %41 ], [ %39, %38 ]
  %45 = icmp eq i32 %44, 0
  br i1 %45, label %48, label %46

46:                                               ; preds = %43
  %47 = phi i32 [ %44, %43 ]
  br label %91

48:                                               ; preds = %43
  %49 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 9, ptr noundef @.str.1)
  %50 = call noundef zeroext i1 @_ZN12CoroutineDef7awaiter11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %21)
  br i1 %50, label %60, label %51

51:                                               ; preds = %48
  %52 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 3
  store i2 1, ptr %52, align 1
  br label %53

53:                                               ; preds = %51
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_await(ptr %21, ptr %15)
  br label %54

54:                                               ; preds = %53
  br label %55

55:                                               ; preds = %54
  br label %56

56:                                               ; preds = %55
  switch i8 -1, label %98 [
    i8 0, label %60
    i8 1, label %57
  ]

57:                                               ; preds = %56
  br label %58

58:                                               ; preds = %57
  %59 = phi i32 [ 2, %57 ]
  br label %63

60:                                               ; preds = %56, %48
  call void @_ZN12CoroutineDef7awaiter12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %21)
  br label %61

61:                                               ; preds = %60
  %62 = phi i32 [ 0, %60 ]
  br label %63

63:                                               ; preds = %61, %58
  %64 = phi i32 [ %62, %61 ], [ %59, %58 ]
  %65 = icmp eq i32 %64, 0
  br i1 %65, label %68, label %66

66:                                               ; preds = %63
  %67 = phi i32 [ %64, %63 ]
  br label %91

68:                                               ; preds = %63
  call void @_ZN12CoroutineDef4task12promise_type11return_voidEv(ptr noundef nonnull align 8 dereferenceable(8) %23)
  br label %69

69:                                               ; preds = %68
  call void @_ZN12CoroutineDef4task12promise_type13final_suspendEv(ptr noundef nonnull align 8 dereferenceable(8) %23) #7
  %70 = call noundef zeroext i1 @_ZNKSt3__113suspend_never11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %22) #7
  br i1 %70, label %80, label %71

71:                                               ; preds = %69
  %72 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %15, i32 0, i32 0
  store ptr null, ptr %72, align 8
  br label %73

73:                                               ; preds = %71
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_final(ptr %22, ptr %15) #7
  br label %74

74:                                               ; preds = %73
  br label %75

75:                                               ; preds = %74
  br label %76

76:                                               ; preds = %75
  switch i8 -1, label %98 [
    i8 0, label %80
    i8 1, label %77
  ]

77:                                               ; preds = %76
  br label %78

78:                                               ; preds = %77
  %79 = phi i32 [ 2, %77 ]
  br label %83

80:                                               ; preds = %76, %69
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %22) #7
  br label %81

81:                                               ; preds = %80
  %82 = phi i32 [ 0, %80 ]
  br label %83

83:                                               ; preds = %81, %78
  %84 = phi i32 [ %82, %81 ], [ %79, %78 ]
  %85 = icmp eq i32 %84, 0
  br i1 %85, label %88, label %86

86:                                               ; preds = %83
  %87 = phi i32 [ %84, %83 ]
  br label %91

88:                                               ; preds = %83
  br label %89

89:                                               ; preds = %88
  %90 = phi i32 [ 0, %88 ]
  br label %91

91:                                               ; preds = %46, %66, %86, %89
  %92 = phi i32 [ %47, %46 ], [ %67, %66 ], [ %87, %86 ], [ %90, %89 ]
  %93 = call noundef ptr @_ZN12CoroutineDef4task12promise_typeD1Ev(ptr noundef nonnull align 8 dereferenceable(8) %23) #7
  %94 = icmp ne ptr %15, null
  br i1 %94, label %95, label %96

95:                                               ; preds = %91
  call void @_ZdlPv(ptr noundef %15) #7
  br label %96

96:                                               ; preds = %91, %95
  switch i32 %92, label %105 [
    i32 0, label %97
    i32 2, label %98
  ]

97:                                               ; preds = %96
  br label %98

98:                                               ; preds = %97, %96, %76, %56, %36
  br label %99

99:                                               ; preds = %98
  br label %100

100:                                              ; preds = %99
  %101 = getelementptr inbounds %"struct.CoroutineDef::task", ptr %1, i32 0, i32 0
  %102 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %101, i32 0, i32 0
  %103 = load ptr, ptr %102, align 8
  %104 = ptrtoint ptr %103 to i64
  ret i64 %104

105:                                              ; preds = %96
  unreachable
}

; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_init(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle.0", align 8
  %6 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %7 = load ptr, ptr %3, align 8
  %8 = load ptr, ptr %4, align 8
  %9 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef4task12promise_typeEE12from_addressB8un170006EPv(ptr noundef %8) #6
  %10 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %6, i32 0, i32 0
  %11 = inttoptr i64 %9 to ptr
  store ptr %11, ptr %10, align 8
  %12 = call i64 @_ZNKSt3__116coroutine_handleIN12CoroutineDef4task12promise_typeEEcvNS0_IvEEB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %13 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %14 = inttoptr i64 %12 to ptr
  store ptr %14, ptr %13, align 8
  %15 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %16 = load ptr, ptr %15, align 8
  %17 = ptrtoint ptr %16 to i64
  call void @_ZNKSt3__113suspend_never13await_suspendB8un170006ENS_16coroutine_handleIvEE(ptr noundef nonnull align 1 dereferenceable(1) %7, i64 %17) #6
  ret void
}

; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_await(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %6 = load ptr, ptr %3, align 8
  %7 = load ptr, ptr %4, align 8
  %8 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef4task12promise_typeEE12from_addressB8un170006EPv(ptr noundef %7) #6
  %9 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %10 = inttoptr i64 %8 to ptr
  store ptr %10, ptr %9, align 8
  %11 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %12 = load ptr, ptr %11, align 8
  %13 = ptrtoint ptr %12 to i64
  call void @_ZN12CoroutineDef7awaiter13await_suspendENSt3__116coroutine_handleINS_4task12promise_typeEEE(ptr noundef nonnull align 1 dereferenceable(1) %6, i64 %13)
  ret void
}

; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_final(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle.0", align 8
  %6 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %7 = load ptr, ptr %3, align 8
  %8 = load ptr, ptr %4, align 8
  %9 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef4task12promise_typeEE12from_addressB8un170006EPv(ptr noundef %8) #6
  %10 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %6, i32 0, i32 0
  %11 = inttoptr i64 %9 to ptr
  store ptr %11, ptr %10, align 8
  %12 = call i64 @_ZNKSt3__116coroutine_handleIN12CoroutineDef4task12promise_typeEEcvNS0_IvEEB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %13 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %14 = inttoptr i64 %12 to ptr
  store ptr %14, ptr %13, align 8
  %15 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %16 = load ptr, ptr %15, align 8
  %17 = ptrtoint ptr %16 to i64
  call void @_ZNKSt3__113suspend_never13await_suspendB8un170006ENS_16coroutine_handleIvEE(ptr noundef nonnull align 1 dereferenceable(1) %7, i64 %17) #6
  ret void
}

; Function Attrs: mustprogress noinline norecurse nounwind optnone ssp
define noundef i32 @main() #5 {
  %1 = alloca i32, align 4
  %2 = alloca %"struct.CoroutineDef::task", align 8
  store i32 0, ptr %1, align 4
  %3 = call i32 (ptr, ...) @printf(ptr noundef @.str.2, ptr noundef @.str.3, ptr noundef @.str.4, ptr noundef @.str.5)
  %4 = call i64 @_ZN12CoroutineRef7coawaitEv()
  %5 = getelementptr inbounds %"struct.CoroutineDef::task", ptr %2, i32 0, i32 0
  %6 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %7 = inttoptr i64 %4 to ptr
  store ptr %7, ptr %6, align 8
  ret i32 0
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define internal fastcc void @_ZN12CoroutineRef7coawaitEv.resume(ptr noundef nonnull align 8 dereferenceable(32) %0) #0 {
  %2 = alloca %"struct.CoroutineDef::task", align 8
  %3 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 4
  %4 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 5
  %5 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 6
  %6 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 2
  br label %76

7:                                                ; preds = %76
  br label %8

8:                                                ; preds = %7
  br label %9

9:                                                ; preds = %8
  switch i8 0, label %73 [
    i8 0, label %13
    i8 1, label %10
  ]

10:                                               ; preds = %9
  br label %11

11:                                               ; preds = %10
  %12 = phi i32 [ 2, %10 ]
  br label %16

13:                                               ; preds = %9
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %3) #6
  br label %14

14:                                               ; preds = %13
  %15 = phi i32 [ 0, %13 ]
  br label %16

16:                                               ; preds = %14, %11
  %17 = phi i32 [ %15, %14 ], [ %12, %11 ]
  %18 = icmp eq i32 %17, 0
  br i1 %18, label %21, label %19

19:                                               ; preds = %16
  %20 = phi i32 [ %17, %16 ]
  br label %66

21:                                               ; preds = %16
  %22 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 9, ptr noundef @.str.1)
  %23 = call noundef zeroext i1 @_ZN12CoroutineDef7awaiter11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br i1 %23, label %35, label %24

24:                                               ; preds = %21
  %25 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 3
  store i2 1, ptr %25, align 1
  br label %26

26:                                               ; preds = %24
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_await(ptr %4, ptr %0)
  br label %27

27:                                               ; preds = %26
  br label %29

28:                                               ; preds = %76
  br label %29

29:                                               ; preds = %28, %27
  %30 = phi i8 [ -1, %27 ], [ 0, %28 ]
  br label %31

31:                                               ; preds = %29
  switch i8 %30, label %73 [
    i8 0, label %35
    i8 1, label %32
  ]

32:                                               ; preds = %31
  br label %33

33:                                               ; preds = %32
  %34 = phi i32 [ 2, %32 ]
  br label %38

35:                                               ; preds = %31, %21
  call void @_ZN12CoroutineDef7awaiter12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br label %36

36:                                               ; preds = %35
  %37 = phi i32 [ 0, %35 ]
  br label %38

38:                                               ; preds = %36, %33
  %39 = phi i32 [ %37, %36 ], [ %34, %33 ]
  %40 = icmp eq i32 %39, 0
  br i1 %40, label %43, label %41

41:                                               ; preds = %38
  %42 = phi i32 [ %39, %38 ]
  br label %66

43:                                               ; preds = %38
  call void @_ZN12CoroutineDef4task12promise_type11return_voidEv(ptr noundef nonnull align 8 dereferenceable(8) %6)
  br label %44

44:                                               ; preds = %43
  call void @_ZN12CoroutineDef4task12promise_type13final_suspendEv(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %45 = call noundef zeroext i1 @_ZNKSt3__113suspend_never11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  br i1 %45, label %55, label %46

46:                                               ; preds = %44
  %47 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 0
  store ptr null, ptr %47, align 8
  br label %48

48:                                               ; preds = %46
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_final(ptr %5, ptr %0) #6
  br label %49

49:                                               ; preds = %48
  br label %50

50:                                               ; preds = %49
  br label %51

51:                                               ; preds = %50
  switch i8 -1, label %73 [
    i8 0, label %55
    i8 1, label %52
  ]

52:                                               ; preds = %51
  br label %53

53:                                               ; preds = %52
  %54 = phi i32 [ 2, %52 ]
  br label %58

55:                                               ; preds = %51, %44
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  br label %56

56:                                               ; preds = %55
  %57 = phi i32 [ 0, %55 ]
  br label %58

58:                                               ; preds = %56, %53
  %59 = phi i32 [ %57, %56 ], [ %54, %53 ]
  %60 = icmp eq i32 %59, 0
  br i1 %60, label %63, label %61

61:                                               ; preds = %58
  %62 = phi i32 [ %59, %58 ]
  br label %66

63:                                               ; preds = %58
  br label %64

64:                                               ; preds = %63
  %65 = phi i32 [ 0, %63 ]
  br label %66

66:                                               ; preds = %64, %61, %41, %19
  %67 = phi i32 [ %20, %19 ], [ %42, %41 ], [ %62, %61 ], [ %65, %64 ]
  %68 = call noundef ptr @_ZN12CoroutineDef4task12promise_typeD1Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %69 = icmp ne ptr %0, null
  br i1 %69, label %70, label %71

70:                                               ; preds = %66
  call void @_ZdlPv(ptr noundef %0) #6
  br label %71

71:                                               ; preds = %70, %66
  switch i32 %67, label %75 [
    i32 0, label %72
    i32 2, label %73
  ]

72:                                               ; preds = %71
  br label %73

73:                                               ; preds = %72, %71, %51, %31, %9
  br label %74

74:                                               ; preds = %73
  ret void

75:                                               ; preds = %71
  unreachable

76:                                               ; preds = %1
  %77 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 3
  %78 = load i2, ptr %77, align 1
  switch i2 %78, label %79 [
    i2 0, label %7
    i2 1, label %28
  ]

79:                                               ; preds = %76
  unreachable
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define internal fastcc void @_ZN12CoroutineRef7coawaitEv.destroy(ptr noundef nonnull align 8 dereferenceable(32) %0) #0 {
  %2 = alloca %"struct.CoroutineDef::task", align 8
  %3 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 4
  %4 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 5
  %5 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 6
  %6 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 2
  br label %78

7:                                                ; preds = %84
  br label %8

8:                                                ; preds = %7
  br label %9

9:                                                ; preds = %8
  switch i8 1, label %75 [
    i8 0, label %13
    i8 1, label %10
  ]

10:                                               ; preds = %9
  br label %11

11:                                               ; preds = %10
  %12 = phi i32 [ 2, %10 ]
  br label %16

13:                                               ; preds = %9
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %3) #6
  br label %14

14:                                               ; preds = %13
  %15 = phi i32 [ 0, %13 ]
  br label %16

16:                                               ; preds = %14, %11
  %17 = phi i32 [ %15, %14 ], [ %12, %11 ]
  %18 = icmp eq i32 %17, 0
  br i1 %18, label %21, label %19

19:                                               ; preds = %16
  %20 = phi i32 [ %17, %16 ]
  br label %68

21:                                               ; preds = %16
  %22 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 9, ptr noundef @.str.1)
  %23 = call noundef zeroext i1 @_ZN12CoroutineDef7awaiter11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br i1 %23, label %35, label %24

24:                                               ; preds = %21
  %25 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 3
  store i2 1, ptr %25, align 1
  br label %26

26:                                               ; preds = %24
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_await(ptr %4, ptr %0)
  br label %27

27:                                               ; preds = %26
  br label %29

28:                                               ; preds = %84
  br label %29

29:                                               ; preds = %28, %27
  %30 = phi i8 [ -1, %27 ], [ 1, %28 ]
  br label %31

31:                                               ; preds = %29
  switch i8 %30, label %75 [
    i8 0, label %35
    i8 1, label %32
  ]

32:                                               ; preds = %31
  br label %33

33:                                               ; preds = %32
  %34 = phi i32 [ 2, %32 ]
  br label %38

35:                                               ; preds = %31, %21
  call void @_ZN12CoroutineDef7awaiter12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br label %36

36:                                               ; preds = %35
  %37 = phi i32 [ 0, %35 ]
  br label %38

38:                                               ; preds = %36, %33
  %39 = phi i32 [ %37, %36 ], [ %34, %33 ]
  %40 = icmp eq i32 %39, 0
  br i1 %40, label %43, label %41

41:                                               ; preds = %38
  %42 = phi i32 [ %39, %38 ]
  br label %68

43:                                               ; preds = %38
  call void @_ZN12CoroutineDef4task12promise_type11return_voidEv(ptr noundef nonnull align 8 dereferenceable(8) %6)
  br label %44

44:                                               ; preds = %43
  call void @_ZN12CoroutineDef4task12promise_type13final_suspendEv(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %45 = call noundef zeroext i1 @_ZNKSt3__113suspend_never11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  br i1 %45, label %57, label %46

46:                                               ; preds = %44
  %47 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 0
  store ptr null, ptr %47, align 8
  br label %48

48:                                               ; preds = %46
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_final(ptr %5, ptr %0) #6
  br label %49

49:                                               ; preds = %48
  br label %51

50:                                               ; preds = %78
  br label %51

51:                                               ; preds = %50, %49
  %52 = phi i8 [ -1, %49 ], [ 1, %50 ]
  br label %53

53:                                               ; preds = %51
  switch i8 %52, label %75 [
    i8 0, label %57
    i8 1, label %54
  ]

54:                                               ; preds = %53
  br label %55

55:                                               ; preds = %54
  %56 = phi i32 [ 2, %54 ]
  br label %60

57:                                               ; preds = %53, %44
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  br label %58

58:                                               ; preds = %57
  %59 = phi i32 [ 0, %57 ]
  br label %60

60:                                               ; preds = %58, %55
  %61 = phi i32 [ %59, %58 ], [ %56, %55 ]
  %62 = icmp eq i32 %61, 0
  br i1 %62, label %65, label %63

63:                                               ; preds = %60
  %64 = phi i32 [ %61, %60 ]
  br label %68

65:                                               ; preds = %60
  br label %66

66:                                               ; preds = %65
  %67 = phi i32 [ 0, %65 ]
  br label %68

68:                                               ; preds = %66, %63, %41, %19
  %69 = phi i32 [ %20, %19 ], [ %42, %41 ], [ %64, %63 ], [ %67, %66 ]
  %70 = call noundef ptr @_ZN12CoroutineDef4task12promise_typeD1Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %71 = icmp ne ptr %0, null
  br i1 %71, label %72, label %73

72:                                               ; preds = %68
  call void @_ZdlPv(ptr noundef %0) #6
  br label %73

73:                                               ; preds = %72, %68
  switch i32 %69, label %77 [
    i32 0, label %74
    i32 2, label %75
  ]

74:                                               ; preds = %73
  br label %75

75:                                               ; preds = %74, %73, %53, %31, %9
  br label %76

76:                                               ; preds = %75
  ret void

77:                                               ; preds = %73
  unreachable

78:                                               ; preds = %1
  %79 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 3
  %80 = load i2, ptr %79, align 1
  %81 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 0
  %82 = load ptr, ptr %81, align 8
  %83 = icmp eq ptr %82, null
  br i1 %83, label %50, label %84

84:                                               ; preds = %78
  switch i2 %80, label %85 [
    i2 0, label %7
    i2 1, label %28
  ]

85:                                               ; preds = %84
  unreachable
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define internal fastcc void @_ZN12CoroutineRef7coawaitEv.cleanup(ptr noundef nonnull align 8 dereferenceable(32) %0) #0 {
  %2 = alloca %"struct.CoroutineDef::task", align 8
  %3 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 4
  %4 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 5
  %5 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 6
  %6 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 2
  br label %78

7:                                                ; preds = %84
  br label %8

8:                                                ; preds = %7
  br label %9

9:                                                ; preds = %8
  switch i8 1, label %75 [
    i8 0, label %13
    i8 1, label %10
  ]

10:                                               ; preds = %9
  br label %11

11:                                               ; preds = %10
  %12 = phi i32 [ 2, %10 ]
  br label %16

13:                                               ; preds = %9
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %3) #6
  br label %14

14:                                               ; preds = %13
  %15 = phi i32 [ 0, %13 ]
  br label %16

16:                                               ; preds = %14, %11
  %17 = phi i32 [ %15, %14 ], [ %12, %11 ]
  %18 = icmp eq i32 %17, 0
  br i1 %18, label %21, label %19

19:                                               ; preds = %16
  %20 = phi i32 [ %17, %16 ]
  br label %68

21:                                               ; preds = %16
  %22 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 9, ptr noundef @.str.1)
  %23 = call noundef zeroext i1 @_ZN12CoroutineDef7awaiter11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br i1 %23, label %35, label %24

24:                                               ; preds = %21
  %25 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 3
  store i2 1, ptr %25, align 1
  br label %26

26:                                               ; preds = %24
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_await(ptr %4, ptr %0)
  br label %27

27:                                               ; preds = %26
  br label %29

28:                                               ; preds = %84
  br label %29

29:                                               ; preds = %28, %27
  %30 = phi i8 [ -1, %27 ], [ 1, %28 ]
  br label %31

31:                                               ; preds = %29
  switch i8 %30, label %75 [
    i8 0, label %35
    i8 1, label %32
  ]

32:                                               ; preds = %31
  br label %33

33:                                               ; preds = %32
  %34 = phi i32 [ 2, %32 ]
  br label %38

35:                                               ; preds = %31, %21
  call void @_ZN12CoroutineDef7awaiter12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br label %36

36:                                               ; preds = %35
  %37 = phi i32 [ 0, %35 ]
  br label %38

38:                                               ; preds = %36, %33
  %39 = phi i32 [ %37, %36 ], [ %34, %33 ]
  %40 = icmp eq i32 %39, 0
  br i1 %40, label %43, label %41

41:                                               ; preds = %38
  %42 = phi i32 [ %39, %38 ]
  br label %68

43:                                               ; preds = %38
  call void @_ZN12CoroutineDef4task12promise_type11return_voidEv(ptr noundef nonnull align 8 dereferenceable(8) %6)
  br label %44

44:                                               ; preds = %43
  call void @_ZN12CoroutineDef4task12promise_type13final_suspendEv(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %45 = call noundef zeroext i1 @_ZNKSt3__113suspend_never11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  br i1 %45, label %57, label %46

46:                                               ; preds = %44
  %47 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 0
  store ptr null, ptr %47, align 8
  br label %48

48:                                               ; preds = %46
  call void @__await_suspend_wrapper__ZN12CoroutineRef7coawaitEv_final(ptr %5, ptr %0) #6
  br label %49

49:                                               ; preds = %48
  br label %51

50:                                               ; preds = %78
  br label %51

51:                                               ; preds = %50, %49
  %52 = phi i8 [ -1, %49 ], [ 1, %50 ]
  br label %53

53:                                               ; preds = %51
  switch i8 %52, label %75 [
    i8 0, label %57
    i8 1, label %54
  ]

54:                                               ; preds = %53
  br label %55

55:                                               ; preds = %54
  %56 = phi i32 [ 2, %54 ]
  br label %60

57:                                               ; preds = %53, %44
  call void @_ZNKSt3__113suspend_never12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  br label %58

58:                                               ; preds = %57
  %59 = phi i32 [ 0, %57 ]
  br label %60

60:                                               ; preds = %58, %55
  %61 = phi i32 [ %59, %58 ], [ %56, %55 ]
  %62 = icmp eq i32 %61, 0
  br i1 %62, label %65, label %63

63:                                               ; preds = %60
  %64 = phi i32 [ %61, %60 ]
  br label %68

65:                                               ; preds = %60
  br label %66

66:                                               ; preds = %65
  %67 = phi i32 [ 0, %65 ]
  br label %68

68:                                               ; preds = %66, %63, %41, %19
  %69 = phi i32 [ %20, %19 ], [ %42, %41 ], [ %64, %63 ], [ %67, %66 ]
  %70 = call noundef ptr @_ZN12CoroutineDef4task12promise_typeD1Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %71 = icmp ne ptr null, null
  br i1 %71, label %72, label %73

72:                                               ; preds = %68
  call void @_ZdlPv(ptr noundef null) #6
  br label %73

73:                                               ; preds = %72, %68
  switch i32 %69, label %77 [
    i32 0, label %74
    i32 2, label %75
  ]

74:                                               ; preds = %73
  br label %75

75:                                               ; preds = %74, %73, %53, %31, %9
  br label %76

76:                                               ; preds = %75
  ret void

77:                                               ; preds = %73
  unreachable

78:                                               ; preds = %1
  %79 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 3
  %80 = load i2, ptr %79, align 1
  %81 = getelementptr inbounds %_ZN12CoroutineRef7coawaitEv.Frame, ptr %0, i32 0, i32 0
  %82 = load ptr, ptr %81, align 8
  %83 = icmp eq ptr %82, null
  br i1 %83, label %50, label %84

84:                                               ; preds = %78
  switch i2 %80, label %85 [
    i2 0, label %7
    i2 1, label %28
  ]

85:                                               ; preds = %84
  unreachable
}

