; Auto generated by ClangVMP v1.1.2

%"struct.CoroutineDef::task_yield_async" = type { %"struct.std::__1::coroutine_handle" }
%"struct.std::__1::coroutine_handle" = type { ptr }
%"struct.CoroutineDef::task_yield_async::promise_type" = type { [128 x i8], i32 }
%"struct.std::__1::suspend_always" = type { i8 }
%"struct.CoroutineDef::task_yield_async::awaiter_async" = type { i8 }
%_ZN12CoroutineRef13coyield_asyncEv.Frame = type { ptr, ptr, %"struct.CoroutineDef::task_yield_async::promise_type", i3, %"struct.std::__1::suspend_always", %"struct.CoroutineDef::task_yield_async::awaiter_async", %"struct.CoroutineDef::task_yield_async::awaiter_async", %"struct.CoroutineDef::task_yield_async::awaiter_async", %"struct.std::__1::suspend_always" }
%"struct.std::__1::coroutine_handle.0" = type { ptr }

@__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv = private unnamed_addr constant [14 x i8] c"coyield_async\00", align 1
@__FUNCTION__.main = private unnamed_addr constant [5 x i8] c"main\00", align 1
; Function Attrs: mustprogress noinline nounwind optnone ssp
define void @_ZN12CoroutineRef13coyield_asyncEv(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async") align 8 %0) #0 {
  %2 = alloca ptr, align 8
  %3 = alloca %"struct.CoroutineDef::task_yield_async::promise_type", align 4
  %4 = alloca %"struct.std::__1::suspend_always", align 1
  %5 = alloca %"struct.std::__1::suspend_always", align 1
  %6 = alloca %"struct.CoroutineDef::task_yield_async::awaiter_async", align 1
  %7 = alloca %"struct.CoroutineDef::task_yield_async::awaiter_async", align 1
  %8 = alloca %"struct.CoroutineDef::task_yield_async::awaiter_async", align 1
  %9 = alloca %"struct.std::__1::suspend_always", align 1
  %10 = alloca %"struct.std::__1::suspend_always", align 1
  store ptr %0, ptr %2, align 8
  br i1 true, label %13, label %11

11:                                               ; preds = %1
  %12 = phi ptr [ null, %1 ]
  br label %17

13:                                               ; preds = %1
  %14 = call noalias noundef nonnull ptr @_Znwm(i64 noundef 160) #6
  br label %15

15:                                               ; preds = %13
  %16 = phi ptr [ %14, %13 ]
  br label %17

17:                                               ; preds = %11, %15
  %18 = phi ptr [ %12, %11 ], [ %16, %15 ]
  %19 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 0
  store ptr @_ZN12CoroutineRef13coyield_asyncEv.resume, ptr %19, align 8
  %20 = select i1 true, ptr @_ZN12CoroutineRef13coyield_asyncEv.destroy, ptr @_ZN12CoroutineRef13coyield_asyncEv.cleanup
  %21 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 1
  store ptr %20, ptr %21, align 8
  br label %22

22:                                               ; preds = %17
  %23 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 4
  %24 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 5
  %25 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 6
  %26 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 7
  %27 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 8
  %28 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 2
  br label %29

29:                                               ; preds = %22
  %30 = call noundef ptr @_ZN12CoroutineDef16task_yield_async12promise_typeC1Ev(ptr noundef nonnull align 4 dereferenceable(132) %28)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type17get_return_objectEv(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async") align 8 %0, ptr noundef nonnull align 4 dereferenceable(132) %28)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type15initial_suspendEv(ptr noundef nonnull align 4 dereferenceable(132) %28)
  %31 = call noundef zeroext i1 @_ZNKSt3__114suspend_always11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %23) #7
  br i1 %31, label %41, label %32

32:                                               ; preds = %29
  %33 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 3
  store i3 0, ptr %33, align 1
  br label %34

34:                                               ; preds = %32
  call void @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_init(ptr %23, ptr %18) #7
  br label %35

35:                                               ; preds = %34
  br label %36

36:                                               ; preds = %35
  br label %37

37:                                               ; preds = %36
  switch i8 -1, label %146 [
    i8 0, label %41
    i8 1, label %38
  ]

38:                                               ; preds = %37
  br label %39

39:                                               ; preds = %38
  %40 = phi i32 [ 2, %38 ]
  br label %44

41:                                               ; preds = %37, %29
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %23) #7
  br label %42

42:                                               ; preds = %41
  %43 = phi i32 [ 0, %41 ]
  br label %44

44:                                               ; preds = %42, %39
  %45 = phi i32 [ %43, %42 ], [ %40, %39 ]
  %46 = icmp eq i32 %45, 0
  br i1 %46, label %49, label %47

47:                                               ; preds = %44
  %48 = phi i32 [ %45, %44 ]
  br label %139

49:                                               ; preds = %44
  %50 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 8, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %24, ptr noundef nonnull align 4 dereferenceable(132) %28, i8 noundef signext 79)
  %51 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %24)
  br i1 %51, label %62, label %52

52:                                               ; preds = %49
  %53 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 3
  store i3 1, ptr %53, align 1
  br label %54

54:                                               ; preds = %52
  %55 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield(ptr %24, ptr %18)
  br i1 %55, label %56, label %62

56:                                               ; preds = %54
  br label %57

57:                                               ; preds = %56
  br label %58

58:                                               ; preds = %57
  switch i8 -1, label %146 [
    i8 0, label %62
    i8 1, label %59
  ]

59:                                               ; preds = %58
  br label %60

60:                                               ; preds = %59
  %61 = phi i32 [ 2, %59 ]
  br label %65

62:                                               ; preds = %58, %54, %49
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %24)
  br label %63

63:                                               ; preds = %62
  %64 = phi i32 [ 0, %62 ]
  br label %65

65:                                               ; preds = %63, %60
  %66 = phi i32 [ %64, %63 ], [ %61, %60 ]
  %67 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %24) #7
  %68 = icmp eq i32 %66, 0
  br i1 %68, label %71, label %69

69:                                               ; preds = %65
  %70 = phi i32 [ %66, %65 ]
  br label %139

71:                                               ; preds = %65
  %72 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 10, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %25, ptr noundef nonnull align 4 dereferenceable(132) %28, i8 noundef signext 75)
  %73 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %25)
  br i1 %73, label %84, label %74

74:                                               ; preds = %71
  %75 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 3
  store i3 2, ptr %75, align 1
  br label %76

76:                                               ; preds = %74
  %77 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield2(ptr %25, ptr %18)
  br i1 %77, label %78, label %84

78:                                               ; preds = %76
  br label %79

79:                                               ; preds = %78
  br label %80

80:                                               ; preds = %79
  switch i8 -1, label %146 [
    i8 0, label %84
    i8 1, label %81
  ]

81:                                               ; preds = %80
  br label %82

82:                                               ; preds = %81
  %83 = phi i32 [ 2, %81 ]
  br label %87

84:                                               ; preds = %80, %76, %71
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %25)
  br label %85

85:                                               ; preds = %84
  %86 = phi i32 [ 0, %84 ]
  br label %87

87:                                               ; preds = %85, %82
  %88 = phi i32 [ %86, %85 ], [ %83, %82 ]
  %89 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %25) #7
  %90 = icmp eq i32 %88, 0
  br i1 %90, label %93, label %91

91:                                               ; preds = %87
  %92 = phi i32 [ %88, %87 ]
  br label %139

93:                                               ; preds = %87
  %94 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 12, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %26, ptr noundef nonnull align 4 dereferenceable(132) %28, i8 noundef signext 46)
  %95 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %26)
  br i1 %95, label %106, label %96

96:                                               ; preds = %93
  %97 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 3
  store i3 3, ptr %97, align 1
  br label %98

98:                                               ; preds = %96
  %99 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield3(ptr %26, ptr %18)
  br i1 %99, label %100, label %106

100:                                              ; preds = %98
  br label %101

101:                                              ; preds = %100
  br label %102

102:                                              ; preds = %101
  switch i8 -1, label %146 [
    i8 0, label %106
    i8 1, label %103
  ]

103:                                              ; preds = %102
  br label %104

104:                                              ; preds = %103
  %105 = phi i32 [ 2, %103 ]
  br label %109

106:                                              ; preds = %102, %98, %93
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %26)
  br label %107

107:                                              ; preds = %106
  %108 = phi i32 [ 0, %106 ]
  br label %109

109:                                              ; preds = %107, %104
  %110 = phi i32 [ %108, %107 ], [ %105, %104 ]
  %111 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %26) #7
  %112 = icmp eq i32 %110, 0
  br i1 %112, label %115, label %113

113:                                              ; preds = %109
  %114 = phi i32 [ %110, %109 ]
  br label %139

115:                                              ; preds = %109
  %116 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 14, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11return_voidEv(ptr noundef nonnull align 4 dereferenceable(132) %28)
  br label %117

117:                                              ; preds = %115
  call void @_ZN12CoroutineDef16task_yield_async12promise_type13final_suspendEv(ptr noundef nonnull align 4 dereferenceable(132) %28) #7
  %118 = call noundef zeroext i1 @_ZNKSt3__114suspend_always11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %27) #7
  br i1 %118, label %128, label %119

119:                                              ; preds = %117
  %120 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %18, i32 0, i32 0
  store ptr null, ptr %120, align 8
  br label %121

121:                                              ; preds = %119
  call void @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_final(ptr %27, ptr %18) #7
  br label %122

122:                                              ; preds = %121
  br label %123

123:                                              ; preds = %122
  br label %124

124:                                              ; preds = %123
  switch i8 -1, label %146 [
    i8 0, label %128
    i8 1, label %125
  ]

125:                                              ; preds = %124
  br label %126

126:                                              ; preds = %125
  %127 = phi i32 [ 2, %125 ]
  br label %131

128:                                              ; preds = %124, %117
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %27) #7
  br label %129

129:                                              ; preds = %128
  %130 = phi i32 [ 0, %128 ]
  br label %131

131:                                              ; preds = %129, %126
  %132 = phi i32 [ %130, %129 ], [ %127, %126 ]
  %133 = icmp eq i32 %132, 0
  br i1 %133, label %136, label %134

134:                                              ; preds = %131
  %135 = phi i32 [ %132, %131 ]
  br label %139

136:                                              ; preds = %131
  br label %137

137:                                              ; preds = %136
  %138 = phi i32 [ 0, %136 ]
  br label %139

139:                                              ; preds = %47, %69, %91, %113, %134, %137
  %140 = phi i32 [ %48, %47 ], [ %70, %69 ], [ %92, %91 ], [ %114, %113 ], [ %135, %134 ], [ %138, %137 ]
  %141 = call noundef ptr @_ZN12CoroutineDef16task_yield_async12promise_typeD1Ev(ptr noundef nonnull align 4 dereferenceable(132) %28) #7
  %142 = icmp ne ptr %18, null
  br i1 %142, label %143, label %144

143:                                              ; preds = %139
  call void @_ZdlPv(ptr noundef %18) #7
  br label %144

144:                                              ; preds = %139, %143
  switch i32 %140, label %149 [
    i32 0, label %145
    i32 2, label %146
  ]

145:                                              ; preds = %144
  br label %146

146:                                              ; preds = %145, %144, %124, %102, %80, %58, %37
  br label %147

147:                                              ; preds = %146
  br label %148

148:                                              ; preds = %147
  ret void

149:                                              ; preds = %144
  unreachable
}

; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_init(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle.0", align 8
  %6 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %7 = load ptr, ptr %3, align 8
  %8 = load ptr, ptr %4, align 8
  %9 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEE12from_addressB8un170006EPv(ptr noundef %8) #6
  %10 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %6, i32 0, i32 0
  %11 = inttoptr i64 %9 to ptr
  store ptr %11, ptr %10, align 8
  %12 = call i64 @_ZNKSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEEcvNS0_IvEEB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %13 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %14 = inttoptr i64 %12 to ptr
  store ptr %14, ptr %13, align 8
  %15 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %16 = load ptr, ptr %15, align 8
  %17 = ptrtoint ptr %16 to i64
  call void @_ZNKSt3__114suspend_always13await_suspendB8un170006ENS_16coroutine_handleIvEE(ptr noundef nonnull align 1 dereferenceable(1) %7, i64 %17) #6
  ret void
}

; Function Attrs: alwaysinline mustprogress
define private noundef i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %6 = load ptr, ptr %3, align 8
  %7 = load ptr, ptr %4, align 8
  %8 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEE12from_addressB8un170006EPv(ptr noundef %7) #6
  %9 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %10 = inttoptr i64 %8 to ptr
  store ptr %10, ptr %9, align 8
  %11 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %12 = load ptr, ptr %11, align 8
  %13 = ptrtoint ptr %12 to i64
  %14 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async13await_suspendENSt3__116coroutine_handleINS0_12promise_typeEEE(ptr noundef nonnull align 1 dereferenceable(1) %6, i64 %13)
  ret i1 %14
}

; Function Attrs: alwaysinline mustprogress
define private noundef i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield2(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %6 = load ptr, ptr %3, align 8
  %7 = load ptr, ptr %4, align 8
  %8 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEE12from_addressB8un170006EPv(ptr noundef %7) #6
  %9 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %10 = inttoptr i64 %8 to ptr
  store ptr %10, ptr %9, align 8
  %11 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %12 = load ptr, ptr %11, align 8
  %13 = ptrtoint ptr %12 to i64
  %14 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async13await_suspendENSt3__116coroutine_handleINS0_12promise_typeEEE(ptr noundef nonnull align 1 dereferenceable(1) %6, i64 %13)
  ret i1 %14
}

; Function Attrs: alwaysinline mustprogress
define private noundef i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield3(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %6 = load ptr, ptr %3, align 8
  %7 = load ptr, ptr %4, align 8
  %8 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEE12from_addressB8un170006EPv(ptr noundef %7) #6
  %9 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %10 = inttoptr i64 %8 to ptr
  store ptr %10, ptr %9, align 8
  %11 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %12 = load ptr, ptr %11, align 8
  %13 = ptrtoint ptr %12 to i64
  %14 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async13await_suspendENSt3__116coroutine_handleINS0_12promise_typeEEE(ptr noundef nonnull align 1 dereferenceable(1) %6, i64 %13)
  ret i1 %14
}

; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_final(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle.0", align 8
  %6 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %7 = load ptr, ptr %3, align 8
  %8 = load ptr, ptr %4, align 8
  %9 = call i64 @_ZNSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEE12from_addressB8un170006EPv(ptr noundef %8) #6
  %10 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %6, i32 0, i32 0
  %11 = inttoptr i64 %9 to ptr
  store ptr %11, ptr %10, align 8
  %12 = call i64 @_ZNKSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEEcvNS0_IvEEB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #6
  %13 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %14 = inttoptr i64 %12 to ptr
  store ptr %14, ptr %13, align 8
  %15 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %16 = load ptr, ptr %15, align 8
  %17 = ptrtoint ptr %16 to i64
  call void @_ZNKSt3__114suspend_always13await_suspendB8un170006ENS_16coroutine_handleIvEE(ptr noundef nonnull align 1 dereferenceable(1) %7, i64 %17) #6
  ret void
}

; Function Attrs: mustprogress noinline norecurse nounwind optnone ssp
define noundef i32 @main() #5 {
  %1 = alloca i32, align 4
  %2 = alloca %"struct.CoroutineDef::task_yield_async", align 8
  store i32 0, ptr %1, align 4
  %3 = call i32 (ptr, ...) @printf(ptr noundef @.str.2, ptr noundef @.str.3, ptr noundef @.str.4, ptr noundef @.str.5)
  call void @_ZN12CoroutineRef13coyield_asyncEv(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async") align 8 %2)
  br label %4

4:                                                ; preds = %8, %0
  %5 = getelementptr inbounds %"struct.CoroutineDef::task_yield_async", ptr %2, i32 0, i32 0
  %6 = call noundef zeroext i1 @_ZNKSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEE4doneB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %5)
  %7 = xor i1 %6, true
  br i1 %7, label %8, label %11

8:                                                ; preds = %4
  %9 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 23, ptr noundef @__FUNCTION__.main)
  %10 = getelementptr inbounds %"struct.CoroutineDef::task_yield_async", ptr %2, i32 0, i32 0
  call void @_ZNKSt3__116coroutine_handleIN12CoroutineDef16task_yield_async12promise_typeEE6resumeB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %10)
  br label %4, !llvm.loop !5

11:                                               ; preds = %4
  %12 = call noundef ptr @_ZN12CoroutineDef16task_yield_async5valueEv(ptr noundef nonnull align 8 dereferenceable(8) %2)
  %13 = call i32 @puts(ptr noundef %12)
  store i32 0, ptr %1, align 4
  %14 = call noundef ptr @_ZN12CoroutineDef16task_yield_asyncD1Ev(ptr noundef nonnull align 8 dereferenceable(8) %2) #6
  %15 = load i32, ptr %1, align 4
  ret i32 %15
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define internal fastcc void @_ZN12CoroutineRef13coyield_asyncEv.resume(ptr noundef nonnull align 8 dereferenceable(160) %0) #0 {
  %2 = alloca ptr, align 8
  %3 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 4
  %4 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 5
  %5 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 6
  %6 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 7
  %7 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 8
  %8 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 2
  br label %129

9:                                                ; preds = %129
  br label %10

10:                                               ; preds = %9
  br label %11

11:                                               ; preds = %10
  switch i8 0, label %126 [
    i8 0, label %15
    i8 1, label %12
  ]

12:                                               ; preds = %11
  br label %13

13:                                               ; preds = %12
  %14 = phi i32 [ 2, %12 ]
  br label %18

15:                                               ; preds = %11
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %3) #6
  br label %16

16:                                               ; preds = %15
  %17 = phi i32 [ 0, %15 ]
  br label %18

18:                                               ; preds = %16, %13
  %19 = phi i32 [ %17, %16 ], [ %14, %13 ]
  %20 = icmp eq i32 %19, 0
  br i1 %20, label %23, label %21

21:                                               ; preds = %18
  %22 = phi i32 [ %19, %18 ]
  br label %119

23:                                               ; preds = %18
  %24 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 8, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %4, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 79)
  %25 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br i1 %25, label %38, label %26

26:                                               ; preds = %23
  %27 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 1, ptr %27, align 1
  br label %28

28:                                               ; preds = %26
  %29 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield(ptr %4, ptr %0)
  br i1 %29, label %30, label %38

30:                                               ; preds = %28
  br label %32

31:                                               ; preds = %129
  br label %32

32:                                               ; preds = %31, %30
  %33 = phi i8 [ -1, %30 ], [ 0, %31 ]
  br label %34

34:                                               ; preds = %32
  switch i8 %33, label %126 [
    i8 0, label %38
    i8 1, label %35
  ]

35:                                               ; preds = %34
  br label %36

36:                                               ; preds = %35
  %37 = phi i32 [ 2, %35 ]
  br label %41

38:                                               ; preds = %34, %28, %23
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br label %39

39:                                               ; preds = %38
  %40 = phi i32 [ 0, %38 ]
  br label %41

41:                                               ; preds = %39, %36
  %42 = phi i32 [ %40, %39 ], [ %37, %36 ]
  %43 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %4) #6
  %44 = icmp eq i32 %42, 0
  br i1 %44, label %47, label %45

45:                                               ; preds = %41
  %46 = phi i32 [ %42, %41 ]
  br label %119

47:                                               ; preds = %41
  %48 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 10, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %5, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 75)
  %49 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %5)
  br i1 %49, label %62, label %50

50:                                               ; preds = %47
  %51 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 2, ptr %51, align 1
  br label %52

52:                                               ; preds = %50
  %53 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield2(ptr %5, ptr %0)
  br i1 %53, label %54, label %62

54:                                               ; preds = %52
  br label %56

55:                                               ; preds = %129
  br label %56

56:                                               ; preds = %55, %54
  %57 = phi i8 [ -1, %54 ], [ 0, %55 ]
  br label %58

58:                                               ; preds = %56
  switch i8 %57, label %126 [
    i8 0, label %62
    i8 1, label %59
  ]

59:                                               ; preds = %58
  br label %60

60:                                               ; preds = %59
  %61 = phi i32 [ 2, %59 ]
  br label %65

62:                                               ; preds = %58, %52, %47
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %5)
  br label %63

63:                                               ; preds = %62
  %64 = phi i32 [ 0, %62 ]
  br label %65

65:                                               ; preds = %63, %60
  %66 = phi i32 [ %64, %63 ], [ %61, %60 ]
  %67 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  %68 = icmp eq i32 %66, 0
  br i1 %68, label %71, label %69

69:                                               ; preds = %65
  %70 = phi i32 [ %66, %65 ]
  br label %119

71:                                               ; preds = %65
  %72 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 12, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %6, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 46)
  %73 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %6)
  br i1 %73, label %86, label %74

74:                                               ; preds = %71
  %75 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 3, ptr %75, align 1
  br label %76

76:                                               ; preds = %74
  %77 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield3(ptr %6, ptr %0)
  br i1 %77, label %78, label %86

78:                                               ; preds = %76
  br label %80

79:                                               ; preds = %129
  br label %80

80:                                               ; preds = %79, %78
  %81 = phi i8 [ -1, %78 ], [ 0, %79 ]
  br label %82

82:                                               ; preds = %80
  switch i8 %81, label %126 [
    i8 0, label %86
    i8 1, label %83
  ]

83:                                               ; preds = %82
  br label %84

84:                                               ; preds = %83
  %85 = phi i32 [ 2, %83 ]
  br label %89

86:                                               ; preds = %82, %76, %71
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %6)
  br label %87

87:                                               ; preds = %86
  %88 = phi i32 [ 0, %86 ]
  br label %89

89:                                               ; preds = %87, %84
  %90 = phi i32 [ %88, %87 ], [ %85, %84 ]
  %91 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %6) #6
  %92 = icmp eq i32 %90, 0
  br i1 %92, label %95, label %93

93:                                               ; preds = %89
  %94 = phi i32 [ %90, %89 ]
  br label %119

95:                                               ; preds = %89
  %96 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 14, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11return_voidEv(ptr noundef nonnull align 4 dereferenceable(132) %8)
  br label %97

97:                                               ; preds = %95
  call void @_ZN12CoroutineDef16task_yield_async12promise_type13final_suspendEv(ptr noundef nonnull align 4 dereferenceable(132) %8) #6
  %98 = call noundef zeroext i1 @_ZNKSt3__114suspend_always11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %7) #6
  br i1 %98, label %108, label %99

99:                                               ; preds = %97
  %100 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 0
  store ptr null, ptr %100, align 8
  br label %101

101:                                              ; preds = %99
  call void @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_final(ptr %7, ptr %0) #6
  br label %102

102:                                              ; preds = %101
  br label %103

103:                                              ; preds = %102
  br label %104

104:                                              ; preds = %103
  switch i8 -1, label %126 [
    i8 0, label %108
    i8 1, label %105
  ]

105:                                              ; preds = %104
  br label %106

106:                                              ; preds = %105
  %107 = phi i32 [ 2, %105 ]
  br label %111

108:                                              ; preds = %104, %97
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %7) #6
  br label %109

109:                                              ; preds = %108
  %110 = phi i32 [ 0, %108 ]
  br label %111

111:                                              ; preds = %109, %106
  %112 = phi i32 [ %110, %109 ], [ %107, %106 ]
  %113 = icmp eq i32 %112, 0
  br i1 %113, label %116, label %114

114:                                              ; preds = %111
  %115 = phi i32 [ %112, %111 ]
  br label %119

116:                                              ; preds = %111
  br label %117

117:                                              ; preds = %116
  %118 = phi i32 [ 0, %116 ]
  br label %119

119:                                              ; preds = %117, %114, %93, %69, %45, %21
  %120 = phi i32 [ %22, %21 ], [ %46, %45 ], [ %70, %69 ], [ %94, %93 ], [ %115, %114 ], [ %118, %117 ]
  %121 = call noundef ptr @_ZN12CoroutineDef16task_yield_async12promise_typeD1Ev(ptr noundef nonnull align 4 dereferenceable(132) %8) #6
  %122 = icmp ne ptr %0, null
  br i1 %122, label %123, label %124

123:                                              ; preds = %119
  call void @_ZdlPv(ptr noundef %0) #6
  br label %124

124:                                              ; preds = %123, %119
  switch i32 %120, label %128 [
    i32 0, label %125
    i32 2, label %126
  ]

125:                                              ; preds = %124
  br label %126

126:                                              ; preds = %125, %124, %104, %82, %58, %34, %11
  br label %127

127:                                              ; preds = %126
  ret void

128:                                              ; preds = %124
  unreachable

129:                                              ; preds = %1
  %130 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  %131 = load i3, ptr %130, align 1
  switch i3 %131, label %132 [
    i3 0, label %9
    i3 1, label %31
    i3 2, label %55
    i3 3, label %79
  ]

132:                                              ; preds = %129
  unreachable
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define internal fastcc void @_ZN12CoroutineRef13coyield_asyncEv.destroy(ptr noundef nonnull align 8 dereferenceable(160) %0) #0 {
  %2 = alloca ptr, align 8
  %3 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 4
  %4 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 5
  %5 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 6
  %6 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 7
  %7 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 8
  %8 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 2
  br label %131

9:                                                ; preds = %137
  br label %10

10:                                               ; preds = %9
  br label %11

11:                                               ; preds = %10
  switch i8 1, label %128 [
    i8 0, label %15
    i8 1, label %12
  ]

12:                                               ; preds = %11
  br label %13

13:                                               ; preds = %12
  %14 = phi i32 [ 2, %12 ]
  br label %18

15:                                               ; preds = %11
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %3) #6
  br label %16

16:                                               ; preds = %15
  %17 = phi i32 [ 0, %15 ]
  br label %18

18:                                               ; preds = %16, %13
  %19 = phi i32 [ %17, %16 ], [ %14, %13 ]
  %20 = icmp eq i32 %19, 0
  br i1 %20, label %23, label %21

21:                                               ; preds = %18
  %22 = phi i32 [ %19, %18 ]
  br label %121

23:                                               ; preds = %18
  %24 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 8, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %4, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 79)
  %25 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br i1 %25, label %38, label %26

26:                                               ; preds = %23
  %27 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 1, ptr %27, align 1
  br label %28

28:                                               ; preds = %26
  %29 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield(ptr %4, ptr %0)
  br i1 %29, label %30, label %38

30:                                               ; preds = %28
  br label %32

31:                                               ; preds = %137
  br label %32

32:                                               ; preds = %31, %30
  %33 = phi i8 [ -1, %30 ], [ 1, %31 ]
  br label %34

34:                                               ; preds = %32
  switch i8 %33, label %128 [
    i8 0, label %38
    i8 1, label %35
  ]

35:                                               ; preds = %34
  br label %36

36:                                               ; preds = %35
  %37 = phi i32 [ 2, %35 ]
  br label %41

38:                                               ; preds = %34, %28, %23
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br label %39

39:                                               ; preds = %38
  %40 = phi i32 [ 0, %38 ]
  br label %41

41:                                               ; preds = %39, %36
  %42 = phi i32 [ %40, %39 ], [ %37, %36 ]
  %43 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %4) #6
  %44 = icmp eq i32 %42, 0
  br i1 %44, label %47, label %45

45:                                               ; preds = %41
  %46 = phi i32 [ %42, %41 ]
  br label %121

47:                                               ; preds = %41
  %48 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 10, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %5, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 75)
  %49 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %5)
  br i1 %49, label %62, label %50

50:                                               ; preds = %47
  %51 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 2, ptr %51, align 1
  br label %52

52:                                               ; preds = %50
  %53 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield2(ptr %5, ptr %0)
  br i1 %53, label %54, label %62

54:                                               ; preds = %52
  br label %56

55:                                               ; preds = %137
  br label %56

56:                                               ; preds = %55, %54
  %57 = phi i8 [ -1, %54 ], [ 1, %55 ]
  br label %58

58:                                               ; preds = %56
  switch i8 %57, label %128 [
    i8 0, label %62
    i8 1, label %59
  ]

59:                                               ; preds = %58
  br label %60

60:                                               ; preds = %59
  %61 = phi i32 [ 2, %59 ]
  br label %65

62:                                               ; preds = %58, %52, %47
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %5)
  br label %63

63:                                               ; preds = %62
  %64 = phi i32 [ 0, %62 ]
  br label %65

65:                                               ; preds = %63, %60
  %66 = phi i32 [ %64, %63 ], [ %61, %60 ]
  %67 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  %68 = icmp eq i32 %66, 0
  br i1 %68, label %71, label %69

69:                                               ; preds = %65
  %70 = phi i32 [ %66, %65 ]
  br label %121

71:                                               ; preds = %65
  %72 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 12, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %6, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 46)
  %73 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %6)
  br i1 %73, label %86, label %74

74:                                               ; preds = %71
  %75 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 3, ptr %75, align 1
  br label %76

76:                                               ; preds = %74
  %77 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield3(ptr %6, ptr %0)
  br i1 %77, label %78, label %86

78:                                               ; preds = %76
  br label %80

79:                                               ; preds = %137
  br label %80

80:                                               ; preds = %79, %78
  %81 = phi i8 [ -1, %78 ], [ 1, %79 ]
  br label %82

82:                                               ; preds = %80
  switch i8 %81, label %128 [
    i8 0, label %86
    i8 1, label %83
  ]

83:                                               ; preds = %82
  br label %84

84:                                               ; preds = %83
  %85 = phi i32 [ 2, %83 ]
  br label %89

86:                                               ; preds = %82, %76, %71
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %6)
  br label %87

87:                                               ; preds = %86
  %88 = phi i32 [ 0, %86 ]
  br label %89

89:                                               ; preds = %87, %84
  %90 = phi i32 [ %88, %87 ], [ %85, %84 ]
  %91 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %6) #6
  %92 = icmp eq i32 %90, 0
  br i1 %92, label %95, label %93

93:                                               ; preds = %89
  %94 = phi i32 [ %90, %89 ]
  br label %121

95:                                               ; preds = %89
  %96 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 14, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11return_voidEv(ptr noundef nonnull align 4 dereferenceable(132) %8)
  br label %97

97:                                               ; preds = %95
  call void @_ZN12CoroutineDef16task_yield_async12promise_type13final_suspendEv(ptr noundef nonnull align 4 dereferenceable(132) %8) #6
  %98 = call noundef zeroext i1 @_ZNKSt3__114suspend_always11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %7) #6
  br i1 %98, label %110, label %99

99:                                               ; preds = %97
  %100 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 0
  store ptr null, ptr %100, align 8
  br label %101

101:                                              ; preds = %99
  call void @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_final(ptr %7, ptr %0) #6
  br label %102

102:                                              ; preds = %101
  br label %104

103:                                              ; preds = %131
  br label %104

104:                                              ; preds = %103, %102
  %105 = phi i8 [ -1, %102 ], [ 1, %103 ]
  br label %106

106:                                              ; preds = %104
  switch i8 %105, label %128 [
    i8 0, label %110
    i8 1, label %107
  ]

107:                                              ; preds = %106
  br label %108

108:                                              ; preds = %107
  %109 = phi i32 [ 2, %107 ]
  br label %113

110:                                              ; preds = %106, %97
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %7) #6
  br label %111

111:                                              ; preds = %110
  %112 = phi i32 [ 0, %110 ]
  br label %113

113:                                              ; preds = %111, %108
  %114 = phi i32 [ %112, %111 ], [ %109, %108 ]
  %115 = icmp eq i32 %114, 0
  br i1 %115, label %118, label %116

116:                                              ; preds = %113
  %117 = phi i32 [ %114, %113 ]
  br label %121

118:                                              ; preds = %113
  br label %119

119:                                              ; preds = %118
  %120 = phi i32 [ 0, %118 ]
  br label %121

121:                                              ; preds = %119, %116, %93, %69, %45, %21
  %122 = phi i32 [ %22, %21 ], [ %46, %45 ], [ %70, %69 ], [ %94, %93 ], [ %117, %116 ], [ %120, %119 ]
  %123 = call noundef ptr @_ZN12CoroutineDef16task_yield_async12promise_typeD1Ev(ptr noundef nonnull align 4 dereferenceable(132) %8) #6
  %124 = icmp ne ptr %0, null
  br i1 %124, label %125, label %126

125:                                              ; preds = %121
  call void @_ZdlPv(ptr noundef %0) #6
  br label %126

126:                                              ; preds = %125, %121
  switch i32 %122, label %130 [
    i32 0, label %127
    i32 2, label %128
  ]

127:                                              ; preds = %126
  br label %128

128:                                              ; preds = %127, %126, %106, %82, %58, %34, %11
  br label %129

129:                                              ; preds = %128
  ret void

130:                                              ; preds = %126
  unreachable

131:                                              ; preds = %1
  %132 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  %133 = load i3, ptr %132, align 1
  %134 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 0
  %135 = load ptr, ptr %134, align 8
  %136 = icmp eq ptr %135, null
  br i1 %136, label %103, label %137

137:                                              ; preds = %131
  switch i3 %133, label %138 [
    i3 0, label %9
    i3 1, label %31
    i3 2, label %55
    i3 3, label %79
  ]

138:                                              ; preds = %137
  unreachable
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define internal fastcc void @_ZN12CoroutineRef13coyield_asyncEv.cleanup(ptr noundef nonnull align 8 dereferenceable(160) %0) #0 {
  %2 = alloca ptr, align 8
  %3 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 4
  %4 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 5
  %5 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 6
  %6 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 7
  %7 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 8
  %8 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 2
  br label %131

9:                                                ; preds = %137
  br label %10

10:                                               ; preds = %9
  br label %11

11:                                               ; preds = %10
  switch i8 1, label %128 [
    i8 0, label %15
    i8 1, label %12
  ]

12:                                               ; preds = %11
  br label %13

13:                                               ; preds = %12
  %14 = phi i32 [ 2, %12 ]
  br label %18

15:                                               ; preds = %11
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %3) #6
  br label %16

16:                                               ; preds = %15
  %17 = phi i32 [ 0, %15 ]
  br label %18

18:                                               ; preds = %16, %13
  %19 = phi i32 [ %17, %16 ], [ %14, %13 ]
  %20 = icmp eq i32 %19, 0
  br i1 %20, label %23, label %21

21:                                               ; preds = %18
  %22 = phi i32 [ %19, %18 ]
  br label %121

23:                                               ; preds = %18
  %24 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 8, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %4, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 79)
  %25 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br i1 %25, label %38, label %26

26:                                               ; preds = %23
  %27 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 1, ptr %27, align 1
  br label %28

28:                                               ; preds = %26
  %29 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield(ptr %4, ptr %0)
  br i1 %29, label %30, label %38

30:                                               ; preds = %28
  br label %32

31:                                               ; preds = %137
  br label %32

32:                                               ; preds = %31, %30
  %33 = phi i8 [ -1, %30 ], [ 1, %31 ]
  br label %34

34:                                               ; preds = %32
  switch i8 %33, label %128 [
    i8 0, label %38
    i8 1, label %35
  ]

35:                                               ; preds = %34
  br label %36

36:                                               ; preds = %35
  %37 = phi i32 [ 2, %35 ]
  br label %41

38:                                               ; preds = %34, %28, %23
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %4)
  br label %39

39:                                               ; preds = %38
  %40 = phi i32 [ 0, %38 ]
  br label %41

41:                                               ; preds = %39, %36
  %42 = phi i32 [ %40, %39 ], [ %37, %36 ]
  %43 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %4) #6
  %44 = icmp eq i32 %42, 0
  br i1 %44, label %47, label %45

45:                                               ; preds = %41
  %46 = phi i32 [ %42, %41 ]
  br label %121

47:                                               ; preds = %41
  %48 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 10, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %5, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 75)
  %49 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %5)
  br i1 %49, label %62, label %50

50:                                               ; preds = %47
  %51 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 2, ptr %51, align 1
  br label %52

52:                                               ; preds = %50
  %53 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield2(ptr %5, ptr %0)
  br i1 %53, label %54, label %62

54:                                               ; preds = %52
  br label %56

55:                                               ; preds = %137
  br label %56

56:                                               ; preds = %55, %54
  %57 = phi i8 [ -1, %54 ], [ 1, %55 ]
  br label %58

58:                                               ; preds = %56
  switch i8 %57, label %128 [
    i8 0, label %62
    i8 1, label %59
  ]

59:                                               ; preds = %58
  br label %60

60:                                               ; preds = %59
  %61 = phi i32 [ 2, %59 ]
  br label %65

62:                                               ; preds = %58, %52, %47
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %5)
  br label %63

63:                                               ; preds = %62
  %64 = phi i32 [ 0, %62 ]
  br label %65

65:                                               ; preds = %63, %60
  %66 = phi i32 [ %64, %63 ], [ %61, %60 ]
  %67 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %5) #6
  %68 = icmp eq i32 %66, 0
  br i1 %68, label %71, label %69

69:                                               ; preds = %65
  %70 = phi i32 [ %66, %65 ]
  br label %121

71:                                               ; preds = %65
  %72 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 12, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11yield_valueEc(ptr dead_on_unwind writable sret(%"struct.CoroutineDef::task_yield_async::awaiter_async") align 1 %6, ptr noundef nonnull align 4 dereferenceable(132) %8, i8 noundef signext 46)
  %73 = call noundef zeroext i1 @_ZN12CoroutineDef16task_yield_async13awaiter_async11await_readyEv(ptr noundef nonnull align 1 dereferenceable(1) %6)
  br i1 %73, label %86, label %74

74:                                               ; preds = %71
  %75 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  store i3 3, ptr %75, align 1
  br label %76

76:                                               ; preds = %74
  %77 = call i1 @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_yield3(ptr %6, ptr %0)
  br i1 %77, label %78, label %86

78:                                               ; preds = %76
  br label %80

79:                                               ; preds = %137
  br label %80

80:                                               ; preds = %79, %78
  %81 = phi i8 [ -1, %78 ], [ 1, %79 ]
  br label %82

82:                                               ; preds = %80
  switch i8 %81, label %128 [
    i8 0, label %86
    i8 1, label %83
  ]

83:                                               ; preds = %82
  br label %84

84:                                               ; preds = %83
  %85 = phi i32 [ 2, %83 ]
  br label %89

86:                                               ; preds = %82, %76, %71
  call void @_ZN12CoroutineDef16task_yield_async13awaiter_async12await_resumeEv(ptr noundef nonnull align 1 dereferenceable(1) %6)
  br label %87

87:                                               ; preds = %86
  %88 = phi i32 [ 0, %86 ]
  br label %89

89:                                               ; preds = %87, %84
  %90 = phi i32 [ %88, %87 ], [ %85, %84 ]
  %91 = call noundef ptr @_ZN12CoroutineDef16task_yield_async13awaiter_asyncD1Ev(ptr noundef nonnull align 1 dereferenceable(1) %6) #6
  %92 = icmp eq i32 %90, 0
  br i1 %92, label %95, label %93

93:                                               ; preds = %89
  %94 = phi i32 [ %90, %89 ]
  br label %121

95:                                               ; preds = %89
  %96 = call i32 (ptr, ...) @printf(ptr noundef @.str, ptr noundef @.str.1, i32 noundef 14, ptr noundef @__FUNCTION__._ZN12CoroutineRef13coyield_asyncEv)
  call void @_ZN12CoroutineDef16task_yield_async12promise_type11return_voidEv(ptr noundef nonnull align 4 dereferenceable(132) %8)
  br label %97

97:                                               ; preds = %95
  call void @_ZN12CoroutineDef16task_yield_async12promise_type13final_suspendEv(ptr noundef nonnull align 4 dereferenceable(132) %8) #6
  %98 = call noundef zeroext i1 @_ZNKSt3__114suspend_always11await_readyB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %7) #6
  br i1 %98, label %110, label %99

99:                                               ; preds = %97
  %100 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 0
  store ptr null, ptr %100, align 8
  br label %101

101:                                              ; preds = %99
  call void @__await_suspend_wrapper__ZN12CoroutineRef13coyield_asyncEv_final(ptr %7, ptr %0) #6
  br label %102

102:                                              ; preds = %101
  br label %104

103:                                              ; preds = %131
  br label %104

104:                                              ; preds = %103, %102
  %105 = phi i8 [ -1, %102 ], [ 1, %103 ]
  br label %106

106:                                              ; preds = %104
  switch i8 %105, label %128 [
    i8 0, label %110
    i8 1, label %107
  ]

107:                                              ; preds = %106
  br label %108

108:                                              ; preds = %107
  %109 = phi i32 [ 2, %107 ]
  br label %113

110:                                              ; preds = %106, %97
  call void @_ZNKSt3__114suspend_always12await_resumeB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %7) #6
  br label %111

111:                                              ; preds = %110
  %112 = phi i32 [ 0, %110 ]
  br label %113

113:                                              ; preds = %111, %108
  %114 = phi i32 [ %112, %111 ], [ %109, %108 ]
  %115 = icmp eq i32 %114, 0
  br i1 %115, label %118, label %116

116:                                              ; preds = %113
  %117 = phi i32 [ %114, %113 ]
  br label %121

118:                                              ; preds = %113
  br label %119

119:                                              ; preds = %118
  %120 = phi i32 [ 0, %118 ]
  br label %121

121:                                              ; preds = %119, %116, %93, %69, %45, %21
  %122 = phi i32 [ %22, %21 ], [ %46, %45 ], [ %70, %69 ], [ %94, %93 ], [ %117, %116 ], [ %120, %119 ]
  %123 = call noundef ptr @_ZN12CoroutineDef16task_yield_async12promise_typeD1Ev(ptr noundef nonnull align 4 dereferenceable(132) %8) #6
  %124 = icmp ne ptr null, null
  br i1 %124, label %125, label %126

125:                                              ; preds = %121
  call void @_ZdlPv(ptr noundef null) #6
  br label %126

126:                                              ; preds = %125, %121
  switch i32 %122, label %130 [
    i32 0, label %127
    i32 2, label %128
  ]

127:                                              ; preds = %126
  br label %128

128:                                              ; preds = %127, %126, %106, %82, %58, %34, %11
  br label %129

129:                                              ; preds = %128
  ret void

130:                                              ; preds = %126
  unreachable

131:                                              ; preds = %1
  %132 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 3
  %133 = load i3, ptr %132, align 1
  %134 = getelementptr inbounds %_ZN12CoroutineRef13coyield_asyncEv.Frame, ptr %0, i32 0, i32 0
  %135 = load ptr, ptr %134, align 8
  %136 = icmp eq ptr %135, null
  br i1 %136, label %103, label %137

137:                                              ; preds = %131
  switch i3 %133, label %138 [
    i3 0, label %9
    i3 1, label %31
    i3 2, label %55
    i3 3, label %79
  ]

138:                                              ; preds = %137
  unreachable
}

