; Auto generated by ClangVMP v1.1.2


; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN9Coroutine4testEv_init(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle.0", align 8
  %6 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %7 = load ptr, ptr %3, align 8
  %8 = load ptr, ptr %4, align 8
  %9 = call i64 @_ZNSt3__116coroutine_handleIN9Coroutine4task12promise_typeEE12from_addressB8un170006EPv(ptr noundef %8) #10
  %10 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %6, i32 0, i32 0
  %11 = inttoptr i64 %9 to ptr
  store ptr %11, ptr %10, align 8
  %12 = call i64 @_ZNKSt3__116coroutine_handleIN9Coroutine4task12promise_typeEEcvNS0_IvEEB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #10
  %13 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %14 = inttoptr i64 %12 to ptr
  store ptr %14, ptr %13, align 8
  %15 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %16 = load ptr, ptr %15, align 8
  %17 = ptrtoint ptr %16 to i64
  call void @_ZNKSt3__113suspend_never13await_suspendB8un170006ENS_16coroutine_handleIvEE(ptr noundef nonnull align 1 dereferenceable(1) %7, i64 %17) #10
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden void @_ZNKSt3__113suspend_never13await_suspendB8un170006ENS_16coroutine_handleIvEE(ptr noundef nonnull align 1 dereferenceable(1) %0, i64 %1) #0 align 2 {
  %3 = alloca %"struct.std::__1::coroutine_handle.0", align 8
  %4 = alloca ptr, align 8
  %5 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %3, i32 0, i32 0
  %6 = inttoptr i64 %1 to ptr
  store ptr %6, ptr %5, align 8
  store ptr %0, ptr %4, align 8
  %7 = load ptr, ptr %4, align 8
  ret void
}

; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN9Coroutine4testEv_await(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %6 = load ptr, ptr %3, align 8
  %7 = load ptr, ptr %4, align 8
  %8 = call i64 @_ZNSt3__116coroutine_handleIN9Coroutine4task12promise_typeEE12from_addressB8un170006EPv(ptr noundef %7) #10
  %9 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %10 = inttoptr i64 %8 to ptr
  store ptr %10, ptr %9, align 8
  %11 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %5, i32 0, i32 0
  %12 = load ptr, ptr %11, align 8
  %13 = ptrtoint ptr %12 to i64
  call void @_ZN9Coroutine7awaiter13await_suspendENSt3__116coroutine_handleINS_4task12promise_typeEEE(ptr noundef nonnull align 1 dereferenceable(1) %6, i64 %13)
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr void @_ZN9Coroutine7awaiter13await_suspendENSt3__116coroutine_handleINS_4task12promise_typeEEE(ptr noundef nonnull align 1 dereferenceable(1) %0, i64 %1) #0 align 2 {
  %3 = alloca %"struct.std::__1::coroutine_handle", align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"class.std::__1::thread", align 8
  %6 = alloca %class.anon, align 8
  %7 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %3, i32 0, i32 0
  %8 = inttoptr i64 %1 to ptr
  store ptr %8, ptr %7, align 8
  store ptr %0, ptr %4, align 8
  %9 = load ptr, ptr %4, align 8
  %10 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__1lsB8un170006INS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc(ptr noundef nonnull align 8 dereferenceable(8) @_ZNSt3__14coutE, ptr noundef @.str.10)
  %11 = getelementptr inbounds %class.anon, ptr %6, i32 0, i32 0
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %11, ptr align 8 %3, i64 8, i1 false)
  %12 = call noundef ptr @_ZNSt3__16threadC1IZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS2_4task12promise_typeEEEEUlvE_JEvEEOT_DpOT0_(ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef nonnull align 8 dereferenceable(8) %6)
  call void @_ZNSt3__16thread6detachEv(ptr noundef nonnull align 8 dereferenceable(8) %5)
  %13 = call noundef ptr @_ZNSt3__16threadD1Ev(ptr noundef nonnull align 8 dereferenceable(8) %5) #10
  %14 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__1lsB8un170006INS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc(ptr noundef nonnull align 8 dereferenceable(8) @_ZNSt3__14coutE, ptr noundef @.str.11)
  ret void
}

; Function Attrs: alwaysinline mustprogress
define private void @__await_suspend_wrapper__ZN9Coroutine4testEv_final(ptr noundef nonnull %0, ptr noundef %1) #2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::coroutine_handle.0", align 8
  %6 = alloca %"struct.std::__1::coroutine_handle", align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %7 = load ptr, ptr %3, align 8
  %8 = load ptr, ptr %4, align 8
  %9 = call i64 @_ZNSt3__116coroutine_handleIN9Coroutine4task12promise_typeEE12from_addressB8un170006EPv(ptr noundef %8) #10
  %10 = getelementptr inbounds %"struct.std::__1::coroutine_handle", ptr %6, i32 0, i32 0
  %11 = inttoptr i64 %9 to ptr
  store ptr %11, ptr %10, align 8
  %12 = call i64 @_ZNKSt3__116coroutine_handleIN9Coroutine4task12promise_typeEEcvNS0_IvEEB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #10
  %13 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %14 = inttoptr i64 %12 to ptr
  store ptr %14, ptr %13, align 8
  %15 = getelementptr inbounds %"struct.std::__1::coroutine_handle.0", ptr %5, i32 0, i32 0
  %16 = load ptr, ptr %15, align 8
  %17 = ptrtoint ptr %16 to i64
  call void @_ZNKSt3__113suspend_never13await_suspendB8un170006ENS_16coroutine_handleIvEE(ptr noundef nonnull align 1 dereferenceable(1) %7, i64 %17) #10
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNSt3__16threadC1IZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS2_4task12promise_typeEEEEUlvE_JEvEEOT_DpOT0_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef nonnull align 8 dereferenceable(8) %1) unnamed_addr #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %5 = load ptr, ptr %3, align 8
  %6 = load ptr, ptr %4, align 8
  %7 = call noundef ptr @_ZNSt3__16threadC2IZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS2_4task12promise_typeEEEEUlvE_JEvEEOT_DpOT0_(ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef nonnull align 8 dereferenceable(8) %6)
  ret ptr %5
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNSt3__16threadC2IZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS2_4task12promise_typeEEEEUlvE_JEvEEOT_DpOT0_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef nonnull align 8 dereferenceable(8) %1) unnamed_addr #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"class.std::__1::unique_ptr", align 8
  %6 = alloca %"class.std::__1::unique_ptr.2", align 8
  %7 = alloca i32, align 4
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %8 = load ptr, ptr %3, align 8
  %9 = call noalias noundef nonnull ptr @_Znwm(i64 noundef 8) #10
  %10 = call noundef ptr @_ZNSt3__115__thread_structC1Ev(ptr noundef nonnull align 8 dereferenceable(8) %9)
  %11 = call noundef ptr @_ZNSt3__110unique_ptrINS_15__thread_structENS_14default_deleteIS1_EEEC1B8un170006ILb1EvEEPS1_(ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef %9) #11
  %12 = call noalias noundef nonnull ptr @_Znwm(i64 noundef 16) #10
  %13 = load ptr, ptr %4, align 8
  %14 = call noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEC1B8un170006IJS5_SC_ETnNS_9enable_ifIXsr4_AndINS_17integral_constantIbXeqsZT_sZT_EEENSD_17_EnableUTypesCtorIJDpT_EEEDpNS_14is_convertibleISJ__SUBSTPACK_EEEE5valueEiE4typeELi0EEEDpOSJ_(ptr noundef nonnull align 8 dereferenceable(16) %12, ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef nonnull align 8 dereferenceable(8) %13) #11
  %15 = call noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEEC1B8un170006ILb1EvEEPSD_(ptr noundef nonnull align 8 dereferenceable(8) %6, ptr noundef %12) #11
  %16 = getelementptr inbounds %"class.std::__1::thread", ptr %8, i32 0, i32 0
  %17 = call noundef ptr @_ZNKSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE3getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #11
  %18 = call noundef i32 @_ZNSt3__122__libcpp_thread_createB8un170006EPP17_opaque_pthread_tPFPvS3_ES3_(ptr noundef %16, ptr noundef @_ZNSt3__114__thread_proxyB8un170006INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEEEEPvSF_, ptr noundef %17)
  store i32 %18, ptr %7, align 4
  %19 = load i32, ptr %7, align 4
  %20 = icmp eq i32 %19, 0
  br i1 %20, label %21, label %23

21:                                               ; preds = %2
  %22 = call noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE7releaseB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #11
  br label %25

23:                                               ; preds = %2
  %24 = load i32, ptr %7, align 4
  call void @_ZNSt3__120__throw_system_errorEiPKc(i32 noundef %24, ptr noundef @.str.12) #12
  unreachable

25:                                               ; preds = %21
  %26 = call noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEED1B8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %6) #11
  %27 = call noundef ptr @_ZNSt3__110unique_ptrINS_15__thread_structENS_14default_deleteIS1_EEED1B8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %5) #11
  ret ptr %8
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEC1B8un170006IJS5_SC_ETnNS_9enable_ifIXsr4_AndINS_17integral_constantIbXeqsZT_sZT_EEENSD_17_EnableUTypesCtorIJDpT_EEEDpNS_14is_convertibleISJ__SUBSTPACK_EEEE5valueEiE4typeELi0EEEDpOSJ_(ptr noundef nonnull returned align 8 dereferenceable(16) %0, ptr noundef nonnull align 8 dereferenceable(8) %1, ptr noundef nonnull align 8 dereferenceable(8) %2) unnamed_addr #0 align 2 {
  %4 = alloca ptr, align 8
  %5 = alloca ptr, align 8
  %6 = alloca ptr, align 8
  store ptr %0, ptr %4, align 8
  store ptr %1, ptr %5, align 8
  store ptr %2, ptr %6, align 8
  %7 = load ptr, ptr %4, align 8
  %8 = load ptr, ptr %5, align 8
  %9 = load ptr, ptr %6, align 8
  %10 = call noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEC2B8un170006IJS5_SC_ETnNS_9enable_ifIXsr4_AndINS_17integral_constantIbXeqsZT_sZT_EEENSD_17_EnableUTypesCtorIJDpT_EEEDpNS_14is_convertibleISJ__SUBSTPACK_EEEE5valueEiE4typeELi0EEEDpOSJ_(ptr noundef nonnull align 8 dereferenceable(16) %7, ptr noundef nonnull align 8 dereferenceable(8) %8, ptr noundef nonnull align 8 dereferenceable(8) %9) #10
  ret ptr %7
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEEC1B8un170006ILb1EvEEPSD_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef %1) unnamed_addr #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %5 = load ptr, ptr %3, align 8
  %6 = load ptr, ptr %4, align 8
  %7 = call noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEEC2B8un170006ILb1EvEEPSD_(ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef %6) #10
  ret ptr %5
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNSt3__114__thread_proxyB8un170006INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEEEEPvSF_(ptr noundef %0) #0 {
  %2 = alloca ptr, align 8
  %3 = alloca %"class.std::__1::unique_ptr.2", align 8
  %4 = alloca %"struct.std::__1::__tuple_indices.8", align 1
  store ptr %0, ptr %2, align 8
  %5 = load ptr, ptr %2, align 8
  %6 = call noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEEC1B8un170006ILb1EvEEPSD_(ptr noundef nonnull align 8 dereferenceable(8) %3, ptr noundef %5) #10
  %7 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__119__thread_local_dataEv()
  %8 = call noundef ptr @_ZNKSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE3getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %3) #10
  %9 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__13getB8un170006ILm0EJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEERNS_13tuple_elementIXT_ENS_5tupleIJDpT0_EEEE4typeERSH_(ptr noundef nonnull align 8 dereferenceable(16) %8) #10
  %10 = call noundef ptr @_ZNSt3__110unique_ptrINS_15__thread_structENS_14default_deleteIS1_EEE7releaseB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %9) #10
  call void @_ZNSt3__121__thread_specific_ptrINS_15__thread_structEE11set_pointerEPS1_(ptr noundef nonnull align 8 dereferenceable(8) %7, ptr noundef %10)
  %11 = call noundef ptr @_ZNKSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE3getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %3) #10
  call void @_ZNSt3__116__thread_executeB8un170006INS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_JETpTnmJEEEvRNS_5tupleIJT_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE(ptr noundef nonnull align 8 dereferenceable(16) %11)
  %12 = call noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEED1B8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %3) #10
  ret ptr null
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNKSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE3getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %"class.std::__1::unique_ptr.2", ptr %3, i32 0, i32 0
  %5 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNKSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE5firstB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %4) #10
  %6 = load ptr, ptr %5, align 8
  ret ptr %6
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE7releaseB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  %3 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %4 = load ptr, ptr %2, align 8
  %5 = getelementptr inbounds %"class.std::__1::unique_ptr.2", ptr %4, i32 0, i32 0
  %6 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE5firstB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %5) #10
  %7 = load ptr, ptr %6, align 8
  store ptr %7, ptr %3, align 8
  %8 = getelementptr inbounds %"class.std::__1::unique_ptr.2", ptr %4, i32 0, i32 0
  %9 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE5firstB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %8) #10
  store ptr null, ptr %9, align 8
  %10 = load ptr, ptr %3, align 8
  ret ptr %10
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEED1B8un170006Ev(ptr noundef nonnull returned align 8 dereferenceable(8) %0) unnamed_addr #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = call noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEED2B8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %3) #10
  ret ptr %3
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEC2B8un170006IJS5_SC_ETnNS_9enable_ifIXsr4_AndINS_17integral_constantIbXeqsZT_sZT_EEENSD_17_EnableUTypesCtorIJDpT_EEEDpNS_14is_convertibleISJ__SUBSTPACK_EEEE5valueEiE4typeELi0EEEDpOSJ_(ptr noundef nonnull returned align 8 dereferenceable(16) %0, ptr noundef nonnull align 8 dereferenceable(8) %1, ptr noundef nonnull align 8 dereferenceable(8) %2) unnamed_addr #0 align 2 {
  %4 = alloca ptr, align 8
  %5 = alloca ptr, align 8
  %6 = alloca ptr, align 8
  %7 = alloca %"struct.std::__1::__tuple_indices", align 1
  %8 = alloca %"struct.std::__1::__tuple_types", align 1
  %9 = alloca %"struct.std::__1::__tuple_indices.8", align 1
  %10 = alloca %"struct.std::__1::__tuple_types.9", align 1
  store ptr %0, ptr %4, align 8
  store ptr %1, ptr %5, align 8
  store ptr %2, ptr %6, align 8
  %11 = load ptr, ptr %4, align 8
  %12 = getelementptr inbounds %"class.std::__1::tuple", ptr %11, i32 0, i32 0
  %13 = load ptr, ptr %5, align 8
  %14 = load ptr, ptr %6, align 8
  %15 = call noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EEC1B8un170006IJLm0ELm1EEJS7_SE_ETpTnmJEJEJS7_SE_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENSI_IJDpT2_EEEDpOT3_(ptr noundef nonnull align 8 dereferenceable(16) %12, ptr noundef nonnull align 8 dereferenceable(8) %13, ptr noundef nonnull align 8 dereferenceable(8) %14) #10
  ret ptr %11
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EEC1B8un170006IJLm0ELm1EEJS7_SE_ETpTnmJEJEJS7_SE_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENSI_IJDpT2_EEEDpOT3_(ptr noundef nonnull returned align 8 dereferenceable(16) %0, ptr noundef nonnull align 8 dereferenceable(8) %1, ptr noundef nonnull align 8 dereferenceable(8) %2) unnamed_addr #0 align 2 {
  %4 = alloca %"struct.std::__1::__tuple_indices", align 1
  %5 = alloca %"struct.std::__1::__tuple_types", align 1
  %6 = alloca %"struct.std::__1::__tuple_indices.8", align 1
  %7 = alloca %"struct.std::__1::__tuple_types.9", align 1
  %8 = alloca ptr, align 8
  %9 = alloca ptr, align 8
  %10 = alloca ptr, align 8
  store ptr %0, ptr %8, align 8
  store ptr %1, ptr %9, align 8
  store ptr %2, ptr %10, align 8
  %11 = load ptr, ptr %8, align 8
  %12 = load ptr, ptr %9, align 8
  %13 = load ptr, ptr %10, align 8
  %14 = call noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EEC2B8un170006IJLm0ELm1EEJS7_SE_ETpTnmJEJEJS7_SE_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENSI_IJDpT2_EEEDpOT3_(ptr noundef nonnull align 8 dereferenceable(16) %11, ptr noundef nonnull align 8 dereferenceable(8) %12, ptr noundef nonnull align 8 dereferenceable(8) %13) #10
  ret ptr %11
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EEC2B8un170006IJLm0ELm1EEJS7_SE_ETpTnmJEJEJS7_SE_EEENS1_IJXspT_EEEENS_13__tuple_typesIJDpT0_EEENS1_IJXspT1_EEEENSI_IJDpT2_EEEDpOT3_(ptr noundef nonnull returned align 8 dereferenceable(16) %0, ptr noundef nonnull align 8 dereferenceable(8) %1, ptr noundef nonnull align 8 dereferenceable(8) %2) unnamed_addr #0 align 2 {
  %4 = alloca %"struct.std::__1::__tuple_indices", align 1
  %5 = alloca %"struct.std::__1::__tuple_types", align 1
  %6 = alloca %"struct.std::__1::__tuple_indices.8", align 1
  %7 = alloca %"struct.std::__1::__tuple_types.9", align 1
  %8 = alloca ptr, align 8
  %9 = alloca ptr, align 8
  %10 = alloca ptr, align 8
  store ptr %0, ptr %8, align 8
  store ptr %1, ptr %9, align 8
  store ptr %2, ptr %10, align 8
  %11 = load ptr, ptr %8, align 8
  %12 = load ptr, ptr %9, align 8
  %13 = call noundef ptr @_ZNSt3__112__tuple_leafILm0ENS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEELb0EEC2B8un170006IS5_vEEOT_(ptr noundef nonnull align 8 dereferenceable(8) %11, ptr noundef nonnull align 8 dereferenceable(8) %12) #10
  %14 = getelementptr inbounds i8, ptr %11, i64 8
  %15 = load ptr, ptr %10, align 8
  %16 = call noundef ptr @_ZNSt3__112__tuple_leafILm1EZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS1_4task12promise_typeEEEEUlvE_Lb0EEC2B8un170006IS7_vEEOT_(ptr noundef nonnull align 8 dereferenceable(8) %14, ptr noundef nonnull align 8 dereferenceable(8) %15) #10
  ret ptr %11
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__112__tuple_leafILm1EZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS1_4task12promise_typeEEEEUlvE_Lb0EEC2B8un170006IS7_vEEOT_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef nonnull align 8 dereferenceable(8) %1) unnamed_addr #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %5 = load ptr, ptr %3, align 8
  %6 = getelementptr inbounds %"class.std::__1::__tuple_leaf.7", ptr %5, i32 0, i32 0
  %7 = load ptr, ptr %4, align 8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %6, ptr align 8 %7, i64 8, i1 false)
  ret ptr %5
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEEC2B8un170006ILb1EvEEPSD_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef %1) unnamed_addr #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca %"struct.std::__1::__value_init_tag", align 1
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %6 = load ptr, ptr %3, align 8
  %7 = getelementptr inbounds %"class.std::__1::unique_ptr.2", ptr %6, i32 0, i32 0
  %8 = call noundef ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEEC1B8un170006IRSF_NS_16__value_init_tagEEEOT_OT0_(ptr noundef nonnull align 8 dereferenceable(8) %7, ptr noundef nonnull align 8 dereferenceable(8) %4, ptr noundef nonnull align 1 dereferenceable(1) %5)
  ret ptr %6
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEEC1B8un170006IRSF_NS_16__value_init_tagEEEOT_OT0_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef nonnull align 8 dereferenceable(8) %1, ptr noundef nonnull align 1 dereferenceable(1) %2) unnamed_addr #0 align 2 {
  %4 = alloca ptr, align 8
  %5 = alloca ptr, align 8
  %6 = alloca ptr, align 8
  store ptr %0, ptr %4, align 8
  store ptr %1, ptr %5, align 8
  store ptr %2, ptr %6, align 8
  %7 = load ptr, ptr %4, align 8
  %8 = load ptr, ptr %5, align 8
  %9 = load ptr, ptr %6, align 8
  %10 = call noundef ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEEC2B8un170006IRSF_NS_16__value_init_tagEEEOT_OT0_(ptr noundef nonnull align 8 dereferenceable(8) %7, ptr noundef nonnull align 8 dereferenceable(8) %8, ptr noundef nonnull align 1 dereferenceable(1) %9)
  ret ptr %7
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEEC2B8un170006IRSF_NS_16__value_init_tagEEEOT_OT0_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef nonnull align 8 dereferenceable(8) %1, ptr noundef nonnull align 1 dereferenceable(1) %2) unnamed_addr #0 align 2 {
  %4 = alloca ptr, align 8
  %5 = alloca ptr, align 8
  %6 = alloca ptr, align 8
  %7 = alloca %"struct.std::__1::__value_init_tag", align 1
  store ptr %0, ptr %4, align 8
  store ptr %1, ptr %5, align 8
  store ptr %2, ptr %6, align 8
  %8 = load ptr, ptr %4, align 8
  %9 = load ptr, ptr %5, align 8
  %10 = call noundef ptr @_ZNSt3__122__compressed_pair_elemIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEELi0ELb0EEC2B8un170006IRSF_vEEOT_(ptr noundef nonnull align 8 dereferenceable(8) %8, ptr noundef nonnull align 8 dereferenceable(8) %9)
  %11 = load ptr, ptr %6, align 8
  %12 = call noundef ptr @_ZNSt3__122__compressed_pair_elemINS_14default_deleteINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS1_IS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEEEELi1ELb1EEC2B8un170006ENS_16__value_init_tagE(ptr noundef nonnull align 1 dereferenceable(1) %8)
  ret ptr %8
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__122__compressed_pair_elemIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEELi0ELb0EEC2B8un170006IRSF_vEEOT_(ptr noundef nonnull returned align 8 dereferenceable(8) %0, ptr noundef nonnull align 8 dereferenceable(8) %1) unnamed_addr #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %5 = load ptr, ptr %3, align 8
  %6 = getelementptr inbounds %"struct.std::__1::__compressed_pair_elem.4", ptr %5, i32 0, i32 0
  %7 = load ptr, ptr %4, align 8
  %8 = load ptr, ptr %7, align 8
  store ptr %8, ptr %6, align 8
  ret ptr %5
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNSt3__122__compressed_pair_elemINS_14default_deleteINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS1_IS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEEEELi1ELb1EEC2B8un170006ENS_16__value_init_tagE(ptr noundef nonnull returned align 1 dereferenceable(1) %0) unnamed_addr #0 align 2 {
  %2 = alloca %"struct.std::__1::__value_init_tag", align 1
  %3 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  %4 = load ptr, ptr %3, align 8
  ret ptr %4
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__13getB8un170006ILm0EJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEERNS_13tuple_elementIXT_ENS_5tupleIJDpT0_EEEE4typeERSH_(ptr noundef nonnull align 8 dereferenceable(16) %0) #0 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %"class.std::__1::tuple", ptr %3, i32 0, i32 0
  %5 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__112__tuple_leafILm0ENS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEELb0EE3getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %4) #10
  ret ptr %5
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden void @_ZNSt3__116__thread_executeB8un170006INS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_JETpTnmJEEEvRNS_5tupleIJT_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE(ptr noundef nonnull align 8 dereferenceable(16) %0) #0 {
  %2 = alloca %"struct.std::__1::__tuple_indices.8", align 1
  %3 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  %4 = load ptr, ptr %3, align 8
  %5 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__13getB8un170006ILm1EJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEERNS_13tuple_elementIXT_ENS_5tupleIJDpT0_EEEE4typeERSH_(ptr noundef nonnull align 8 dereferenceable(16) %4) #10
  call void @_ZNSt3__18__invokeB8un170006IZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS1_4task12promise_typeEEEEUlvE_JEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOS8_DpOS9_(ptr noundef nonnull align 8 dereferenceable(8) %5)
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden void @_ZNSt3__18__invokeB8un170006IZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS1_4task12promise_typeEEEEUlvE_JEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOS8_DpOS9_(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  call void @_ZZN9Coroutine7awaiter13await_suspendENSt3__116coroutine_handleINS_4task12promise_typeEEEENUlvE_clEv(ptr noundef nonnull align 8 dereferenceable(8) %3)
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__13getB8un170006ILm1EJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEERNS_13tuple_elementIXT_ENS_5tupleIJDpT0_EEEE4typeERSH_(ptr noundef nonnull align 8 dereferenceable(16) %0) #0 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %"class.std::__1::tuple", ptr %3, i32 0, i32 0
  %5 = getelementptr inbounds i8, ptr %4, i64 8
  %6 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__112__tuple_leafILm1EZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS1_4task12promise_typeEEEEUlvE_Lb0EE3getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %5) #10
  ret ptr %6
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr void @_ZZN9Coroutine7awaiter13await_suspendENSt3__116coroutine_handleINS_4task12promise_typeEEEENUlvE_clEv(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %class.anon, ptr %3, i32 0, i32 0
  call void @_ZNKSt3__116coroutine_handleIN9Coroutine4task12promise_typeEEclB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %4)
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__112__tuple_leafILm1EZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS1_4task12promise_typeEEEEUlvE_Lb0EE3getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %"class.std::__1::__tuple_leaf.7", ptr %3, i32 0, i32 0
  ret ptr %4
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 8 dereferenceable(8) ptr @_ZNKSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE5firstB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNKSt3__122__compressed_pair_elemIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEELi0ELb0EE5__getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %3) #10
  ret ptr %4
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 8 dereferenceable(8) ptr @_ZNKSt3__122__compressed_pair_elemIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEELi0ELb0EE5__getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %"struct.std::__1::__compressed_pair_elem.4", ptr %3, i32 0, i32 0
  ret ptr %4
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE5firstB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__122__compressed_pair_elemIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEELi0ELb0EE5__getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %3) #10
  ret ptr %4
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__122__compressed_pair_elemIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEELi0ELb0EE5__getB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %"struct.std::__1::__compressed_pair_elem.4", ptr %3, i32 0, i32 0
  ret ptr %4
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef ptr @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEED2B8un170006Ev(ptr noundef nonnull returned align 8 dereferenceable(8) %0) unnamed_addr #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  call void @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE5resetB8un170006EPSD_(ptr noundef nonnull align 8 dereferenceable(8) %3, ptr noundef null) #10
  ret ptr %3
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden void @_ZNSt3__110unique_ptrINS_5tupleIJNS0_INS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEENS3_ISD_EEE5resetB8un170006EPSD_(ptr noundef nonnull align 8 dereferenceable(8) %0, ptr noundef %1) #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  %5 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %6 = load ptr, ptr %3, align 8
  %7 = getelementptr inbounds %"class.std::__1::unique_ptr.2", ptr %6, i32 0, i32 0
  %8 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE5firstB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %7) #10
  %9 = load ptr, ptr %8, align 8
  store ptr %9, ptr %5, align 8
  %10 = load ptr, ptr %4, align 8
  %11 = getelementptr inbounds %"class.std::__1::unique_ptr.2", ptr %6, i32 0, i32 0
  %12 = call noundef nonnull align 8 dereferenceable(8) ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE5firstB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %11) #10
  store ptr %10, ptr %12, align 8
  %13 = load ptr, ptr %5, align 8
  %14 = icmp ne ptr %13, null
  br i1 %14, label %15, label %19

15:                                               ; preds = %2
  %16 = getelementptr inbounds %"class.std::__1::unique_ptr.2", ptr %6, i32 0, i32 0
  %17 = call noundef nonnull align 1 dereferenceable(1) ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE6secondB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %16) #10
  %18 = load ptr, ptr %5, align 8
  call void @_ZNKSt3__114default_deleteINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS0_IS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEEEclB8un170006EPSD_(ptr noundef nonnull align 1 dereferenceable(1) %17, ptr noundef %18) #10
  br label %19

19:                                               ; preds = %15, %2
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 1 dereferenceable(1) ptr @_ZNSt3__117__compressed_pairIPNS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEENS4_ISE_EEE6secondB8un170006Ev(ptr noundef nonnull align 8 dereferenceable(8) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = call noundef nonnull align 1 dereferenceable(1) ptr @_ZNSt3__122__compressed_pair_elemINS_14default_deleteINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS1_IS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEEEELi1ELb1EE5__getB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %3) #10
  ret ptr %4
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden void @_ZNKSt3__114default_deleteINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS0_IS3_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EEEEclB8un170006EPSD_(ptr noundef nonnull align 1 dereferenceable(1) %0, ptr noundef %1) #0 align 2 {
  %3 = alloca ptr, align 8
  %4 = alloca ptr, align 8
  store ptr %0, ptr %3, align 8
  store ptr %1, ptr %4, align 8
  %5 = load ptr, ptr %3, align 8
  %6 = load ptr, ptr %4, align 8
  %7 = icmp eq ptr %6, null
  br i1 %7, label %10, label %8

8:                                                ; preds = %2
  %9 = call noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EED1Ev(ptr noundef nonnull align 8 dereferenceable(16) %6) #10
  call void @_ZdlPv(ptr noundef %6) #11
  br label %10

10:                                               ; preds = %8, %2
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr hidden noundef nonnull align 1 dereferenceable(1) ptr @_ZNSt3__122__compressed_pair_elemINS_14default_deleteINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS1_IS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS7_4task12promise_typeEEEEUlvE_EEEEELi1ELb1EE5__getB8un170006Ev(ptr noundef nonnull align 1 dereferenceable(1) %0) #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  ret ptr %3
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EED1Ev(ptr noundef nonnull returned align 8 dereferenceable(16) %0) unnamed_addr #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = call noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EED2Ev(ptr noundef nonnull align 8 dereferenceable(16) %3) #10
  ret ptr %3
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__15tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS6_4task12promise_typeEEEEUlvE_EED2Ev(ptr noundef nonnull returned align 8 dereferenceable(16) %0) unnamed_addr #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = getelementptr inbounds %"class.std::__1::tuple", ptr %3, i32 0, i32 0
  %5 = call noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EED1Ev(ptr noundef nonnull align 8 dereferenceable(16) %4) #10
  ret ptr %3
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EED1Ev(ptr noundef nonnull returned align 8 dereferenceable(16) %0) unnamed_addr #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = call noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EED2Ev(ptr noundef nonnull align 8 dereferenceable(16) %3) #10
  ret ptr %3
}

; Function Attrs: mustprogress noinline nounwind optnone ssp
define linkonce_odr noundef ptr @_ZNSt3__112__tuple_implINS_15__tuple_indicesIJLm0ELm1EEEEJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS4_EEEEZN9Coroutine7awaiter13await_suspendENS_16coroutine_handleINS8_4task12promise_typeEEEEUlvE_EED2Ev(ptr noundef nonnull returned align 8 dereferenceable(16) %0) unnamed_addr #0 align 2 {
  %2 = alloca ptr, align 8
  store ptr %0, ptr %2, align 8
  %3 = load ptr, ptr %2, align 8
  %4 = call noundef ptr @_ZNSt3__112__tuple_leafILm0ENS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEELb0EED2Ev(ptr noundef nonnull align 8 dereferenceable(8) %3) #10
  ret ptr %3
}

